[package]

name = "jsonway"
version = "1.0.0"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]
description = "JSON building DSL and configurable serializers for Rust"
keywords = ["json", "serializers"]
license = "MIT"

[dependencies]
serde = "0.8"
serde_json = "0.8"

[[test]]
name = "tests"
